server:
  port: 8011

spring:
  application:
    name: cloud-nacos-payment-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
