server:
  port: 8017

spring:
  application:
    name: alibaba-sentinel-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'