server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-server-7001.com:7001/eureka,http://eureka-server-7002.com:7002/eureka

  instance:
    instance-id: openfeign-order-80
    prefer-ip-address: true

#openfeign 2.2.1版本 解决超时  不会自动显示 但是两种操作都能正常完成超时问题的解决
# ribbon: ReadTimeout: 5000 ConnectTimeout: 5000
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 120000
#        read-timeout: 120000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
spring:
  application:
    name: cloud-openfeign-order-service
  #    zipkin and sleuth
  zipkin:
    base-url: http://175.178.195.135:9411/
  sleuth:
    sampler:
      #      采集器介值于 0-1 , 1 为全采
      probability: 1

#      ======  zipkin and sleuth  =====


logging:
  level:
    com.lin.service.* : debug
