
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto

  type-aliases-package: com.lin.pojo
  type-enums-package: com.lin.enums