server:
  port: 8007

spring:
  application:
    name: cloud-rabbitmq-provider-service
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: sc-stream-exchange
          content-type: application/json
          binder:
            - ${spring.cloud.stream.binders.defaultRabbit}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-server-7001.com:7001/eureka,http://eureka-server-7002.com:7002/eureka

  instance:
    instance-id: cloud-rabbitmq-provider-8007
    prefer-ip-address: true

