server:
  port: 7002

eureka:
  instance:
    hostname: eureka-server-7002.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server-7001.com:7001/eureka/