server:
  port: 7003
spring:
  application:
    name: seata-account-samples

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


#  mybatis:
#    mapperLocations: classpath:mapper/*.xml
#    type-aliases-package: com.lin.account.entities    # 所有Entity别名类所在包
  cloud:
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 7d1344d5-c048-40da-91d6-77a1d4114123


seata:
  application-id: ${spring.application.name}
  service:
    vgroup-mapping:
      seata-account-samples-tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: 7d1344d5-c048-40da-91d6-77a1d4114123
      #      seata 服务名
      application: seata-server
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: 7d1344d5-c048-40da-91d6-77a1d4114123


feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lin.account.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

