server:
  port: 8008

spring:
  application:
    name: cloud-rabbitmq-consumer-service
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
#        消费者 此处需要修改
        input:
          destination: sc-stream-exchange
          content-type: application/json
#        binder: defaultRabbit
          binder:
            - ${spring.cloud.stream.binders.defaultRabbit}
          group: sc-stream-grop-A


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-server-7001.com:7001/eureka,http://eureka-server-7002.com:7002/eureka

  instance:
    instance-id: cloud-rabbitmq-consumer-8008
    prefer-ip-address: true

