server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-server-7001.com:7001/eureka,http://eureka-server-7002.com:7002/eureka

  instance:
    instance-id: cloud-consumer-order-hystrix-80
    prefer-ip-address: true

#解决openfeign 超时问题
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#开启hystrix 默认为false
feign:
  hystrix:
    enabled: true
